name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: docker-compose up -d

      - name: Wait for app to be ready
        uses: jakejarvis/wait-action@master
        with:
          url: "http://localhost:3000"
          timeout: 60

      - uses: cypress-io/github-action@v6
        with:
          install: false
          start: ""
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60
