name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      backend:
        image: toporu/unq_desasof:1.0.0
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -f http://localhost:8000/docs || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Serve app
        run: npx vite preview --port 3000 &
        env:
          CI: true

      - name: Wait for app to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: http://localhost:3000
          timeout: 60

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60
